import numpy as np
import cv2

img = cv2.imread('/Users/adityakumar/Downloads/wallpaper/BingWallpaper-2018-04-17.jpg')
#retval, thresh = cv2.threshold(img, 50, 255, cv2.THRESH_BINARY)
grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#retval1, thresh1 = cv2.threshold(grayscale, 50, 255, cv2.THRESH_BINARY)
gauss = cv2.adaptiveThreshold(grayscale, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 101, 1)
#gauss1 = cv2.adaptiveThreshold(grayscale, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 101, 1)
#gauss2 = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 101, 1)
#retval2, thresh2 = cv2.threshold(grayscale, 50, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
#blur = cv2.GaussianBlur(grayscale,(5,5),0)
#retval3, thresh3 = cv2.threshold(blur, 50, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
#cv2.imshow('thresh', thresh)
#cv2.imshow('img', img)
#cv2.imshow('gray', grayscale)
#cv2.imshow('thresh1', thresh1)
cv2.imshow('GAUSS', gauss)
#cv2.imshow('blur', blur)
#cv2.imshow('otsu1', thresh3)
#cv2.imshow('otsu', thresh2)
#cv2.imshow('GAUSS1', gauss1)
#cv2.imshow('GAUSS2', gauss2)
#cv2.imwrite('img.jpg', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
